# Generated by Django 3.1.3 on 2020-11-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('seeking', '募集中'), ('requested', '承認待ち'), ('accepted', '承認済み')], default='seeking', max_length=10),
        ),
    ]
