# Generated by Django 3.1.2 on 2020-11-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201103_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', 'その他')], default='male', max_length=10),
        ),
    ]
