# Generated by Django 3.1.2 on 2020-11-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
                ('research', models.TextField(max_length=300)),
                ('sex', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=100)),
                ('self_introduction', models.TextField(max_length=300, null=True)),
                ('birthday', models.DateField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
