# Generated by Django 3.1.2 on 2020-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('research', models.TextField(max_length=300)),
                ('sex', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=100)),
                ('self_introduction', models.TextField(max_length=300)),
            ],
        ),
    ]
